### ISSUE TITLE
Explanatory Agent to keep track of batch predicates

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/minihackathons#10]
Hi Rosina,

This issue is for the action item from the mini-hack on May 20, 2021 to keep track of batch predicate updates that Explanatory agent is planning to do. 

Chris B and Anne would like to revisit the queries ran during the last mini-hackathon at the next week's mini-hackathon (June 3). Would you be able to provide details?

**Comment by tursynay** [comment]
@Rosinaweber , I wanted to follow up about this issue as we have the mini hackathon this week. Was there an update on the batch predicates with explanatory agent? thanks.

**Comment by Rosinaweber** [comment]
It will be in the next version, but we have a formal version release process, and right now it is in the hands of the development team. I will let you know when it is released. Thanks.

**Comment by Rosinaweber** [comment]
Dear Tursynay:
The explanatory Agent is now executing queries with batch predicates.
Note the production server is currently down but is expected to be restored by tonight. Let me know if you want to see an example before closing this PR.
Thanks,
Rosina-

**Comment by tursynay** [comment]
Hi Rosina, thank you for getting back. No need for examples, I can close this issue. If there is a problem, we can either reopen this or create a new issue. Thank you.
