### ISSUE TITLE
How do we handle gene and protein query: conflations

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/minihackathons#12]
Issues occur with gene and protein when queries are ran. Chris B suggested that there should be a way to tell the query to "conflate" or "not conflate" in certain cases. 
Data Modeling group to define conflations formally, and ARAs to implement these formal conflations. This ticket to monitor the progress of this.

**Comment by nlharris** [comment]
@sierra-moxon

**Comment by tursynay** [comment]
@sierra-moxon and @nlharris , I wanted to follow up about this, we have the mini-hackathon this week. Based on the notes from DM call last week, I am not certain what the decision was for conflation (sorry I missed the meeting and did not get the update added to this issue). Has there been progress on this? Thank you.

**Comment by sierra-moxon** [comment]
@tursynay - This is on @cmungall's radar and is a topic for DM calls. I think the main idea is to make a configuration file to specify property chain inference that folks can pick up and reason with.   It will take some work from Chris to seed this, and then we'll be able to pick it up and run with it.  But I will be sure to follow up with him this week.

**Comment by tursynay** [comment]
@sierra-moxon , is this a good issues to keep track of this particular question? https://github.com/biolink/biolink-model/issues/638

**Comment by sierra-moxon** [comment]
@tursynay  - sounds good. :). @cmungall submitted (and this has been released in biolink-model v.2.0.2), a first draft at property chain/conflation specification: https://github.com/biolink/biolink-model/pull/763

**Comment by vgardner-renci** [comment]
Gene/Protein data available mid July. Property chains avail mid July. ARA implementation end of July.

**Comment by vgardner-renci** [comment]
Tag for "July"

**Comment by tursynay** [comment]
At DM call, we changed this a bit, we don't rely on property chains, but going about using the node norm. Some changes must happen to Node Norm to handle this. Expected in mid August. Once done, there should not be any work needed on anyone's end as long as they are using Node Norm. Node Norm will handle it. Aug 15.

**Comment by vgardner-renci** [comment]
@cbizon this issue is a dependency for a few others. Can you weigh in on the status?

**Comment by cbizon** [comment]
We have a prototype node-normalizer that handles gene/protein conflation, demoed on the arch call this week.    Hoping to deploy it this week as well, though it may be next week.

**Comment by vgardner-renci** [comment]
@cbizon Was the NN deployed?

**Comment by cbizon** [comment]
not yet

**Comment by gloriachin** [comment]
It is also related to the issue here. Genetic variance, gene expression level, protein level or post-translational level for one gene should be distinction using some standard way. Matt has proposed a qualifier schema which I think makes a lot of sence. https://github.com/biolink/biolink-model/issues/765#issuecomment-895429373
