### ISSUE TITLE
Error from COHD and ICEES for Workflow D.2 query

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#126]
https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowD/ssri-heart-disease.json

https://arax.ncats.io/?source=ARS&id=9938906a-6f8e-4886-b454-66f5372c81ae

![image](https://user-images.githubusercontent.com/83781286/124972828-cf6f6680-dff8-11eb-913b-a1a269be84bf.png)

**Comment by vgardner-renci** [comment]
ICEES

``
{
  "callback": "http://localhost:8000/ars/api/messages/6559b67f-48cc-40c0-ba7e-35cd502e5463",
  "logs": [
    {
      "level": "INFO",
      "message": "ARS info: &lt;html&gt;&lt;title&gt;405: Method Not Allowed&lt;/title&gt;&lt;body&gt;405: Method Not Allowed&lt;/body&gt;&lt;/html&gt;"
    },
    {
      "level": "INFO",
      "message": "ARS info: tr_ars.Server: nginx/1.14.0 (Ubuntu)"
    },
    {
      "level": "INFO",
      "message": "ARS info: tr_ars.Date: Thu, 08 Jul 2021 15:58:35 GMT"
    },
    {
      "level": "INFO",
      "message": "ARS info: tr_ars.Content-Type: text/html; charset=UTF-8"
    },
    {
      "level": "INFO",
      "message": "ARS info: tr_ars.Content-Length: 87"
    },
    {
      "level": "INFO",
      "message": "ARS info: tr_ars.Connection: keep-alive"
    },
    {
      "level": "INFO",
      "message": "ARS info: tr_ars.reason: Method Not Allowed"
    },
    {
      "level": "INFO",
      "message": "ARS info: tr_ars.url: https://smart-api.info/query?reasoner=true&verbose=false"
    }
  ],
  "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "object": "n01",
          "subject": "n00"
        },
        "e01": {
          "object": "n02",
          "subject": "n01"
        }
      },
      "nodes": {
        "n00": {
          "categories": [
            "biolink:ChemicalSubstance"
          ],
          "ids": [
            "DRUGBANK:DB00215",
            "DRUGBANK:DB01175",
            "DRUGBANK:DB00472",
            "DRUGBANK:DB00176",
            "DRUGBANK:DB00715",
            "DRUGBANK:DB01104"
          ]
        },
        "n01": {
          "categories": [
            "biolink:Gene"
          ]
        },
        "n02": {
          "categories": [
            "biolink:Disease"
          ],
          "ids": [
            "DOID:114"
          ]
        }
      }
    }
  },
  "validation_result": {
    "message": "Returned response is not TRAPI: &lt;html&gt;&lt;title&gt;405: Method Not Allowed&lt;/title&gt;&lt;body&gt;405: Method Not Allowed&lt;/body&gt;&lt;/html&gt;",
    "size": "2 kB",
    "status": "NA",
    "version": "1.1.1"
  }
}

**Comment by vgardner-renci** [comment]
**COHD**

``
{
  "callback": "http://localhost:8000/ars/api/messages/cdfd2bf5-fde9-4012-ae45-c65934f51676",
  "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "object": "n01",
          "subject": "n00"
        },
        "e01": {
          "object": "n02",
          "subject": "n01"
        }
      },
      "nodes": {
        "n00": {
          "categories": [
            "biolink:ChemicalSubstance"
          ],
          "ids": [
            "DRUGBANK:DB00215",
            "DRUGBANK:DB01175",
            "DRUGBANK:DB00472",
            "DRUGBANK:DB00176",
            "DRUGBANK:DB00715",
            "DRUGBANK:DB01104"
          ]
        },
        "n01": {
          "categories": [
            "biolink:Gene"
          ]
        },
        "n02": {
          "categories": [
            "biolink:Disease"
          ],
          "ids": [
            "DOID:114"
          ]
        }
      }
    }
  },
  "validation_result": {
    "message": "",
    "size": "1 kB",
    "status": "PASS",
    "version": "1.1.1"
  }
}

**Comment by karafecho** [comment]
For ICEES, this should work on the dev server. Please note that the message should hit both the ICEES asthma instance (https://icees.renci.org:16339) and the DILI asthma instance (https://icees.renci.org:16341). The message works when sent directly to the ICEES API using the post method.

**Comment by CaseyTa** [comment]
Hi @vgardner-renci, COHD does not support multi-hop queries. Thanks!

**Comment by vgardner-renci** [comment]
@cbizon What action should be taken on this issue?

**Comment by tursynay** [comment]
closing
