### ISSUE TITLE
ARAX -- Infores:diseases is not in the infores list

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#127]
Infores:diseases is not in the infores list. I think this represents the biothings-diseases endpoint? (In infores, we called that infores:biothings-diseases). 

Feedback welcome: https://docs.google.com/spreadsheets/d/1Ma4U3aY16mJushsW74vf9mWVacFvf7FiTEdlVqaUi5g/edit#gid=1644860829

**Comment by edeutsch** [comment]
Hi @vgardner-renci , we are having trouble finding where this a problem. Do you have a query that reproduces this issue that we can examine?

**Comment by edeutsch** [comment]
Hi, we found the source of the issue. We do find an entry called "diseases" in the "External" tab of the workbook. Cell F42.
this is what we are trying to reference. Is that not approved?
![image](https://user-images.githubusercontent.com/12707718/124999566-46116180-e003-11eb-8824-f2a8795918a5.png)

Does the entry in External need to be moved to TranslatorResources?

**Comment by vgardner-renci** [comment]
@sierra-moxon request for comment

**Comment by sierra-moxon** [comment]
@edeutsch - you are right, it is there.  Closing as fixed.
