### ISSUE TITLE
Query returns results that don't match the query 

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/minihackathons#13]
Hi Jim, this issue is to keep track of the development of the below issue. During mini-hack on 05/20/21 the below query was ran Chris B asked if you could look into the result below:

Query returns results that don't match the query 

Query:
qg = {
"nodes": {
"n0": {
"categories": [
"biolink:ChemicalSubstance"
],
"name": "Chemical Substance"
},
"n1": {
"name": "EGFR",
"ids": ["NCBIGene:1956"]
}
},
"edges": {
"e0": {
"subject": "n0",
"object": "n1",
"predicates": [
"biolink:decreases_abundance_of",
"biolink:decreases_activity_of",
"biolink:decreases_expression_of",
"biolink:decreases_synthesis_of",
"biolink:increases_degradation_of",
"biolink:disrupts",
"biolink:negatively_regulates_entity_to_entity"
]
}
}
}

**Comment by tursynay** [comment]
@balhoff, it is for CAM-KP

**Comment by cbizon** [comment]
CAM-KP is now returning no results (expected).
