### ISSUE TITLE
Text mining provider not returning results

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/minihackathons#14]
Query:
qg = {
qg = {
  "nodes": {
    "n0": {
      "categories": [
        "biolink:ChemicalSubstance"
      ],
      "name": "Chemical Substance"
    },
    "n1": {
      "name": "EGFR",
      "ids": ["PR:000006933"]
    }
  },
  "edges": {
    "e0": {
      "subject": "n0",
      "object": "n1",
      "predicates": [
        "biolink:negatively_regulates_entity_to_entity",
        "biolink:entity_negatively_regulates_entity"
      ]
    }
  }
}

EGFR_query_4 = {'message':{'query_graph':qg}}

**Comment by tursynay** [comment]
@bill-baumgardner, this comment makes it sound this issue may be now resolved. please confirm. 
https://github.com/NCATSTranslator/testing/issues/66#issuecomment-850508658

**Comment by tursynay** [comment]
@bill-baumgardner, this comment makes it sound this issue may be now resolved. please confirm. 
https://github.com/NCATSTranslator/testing/issues/66#issuecomment-850508658

**Comment by tursynay** [comment]
@bill-baumgartner , wanted to follow up. Any updates?

**Comment by bill-baumgartner** [comment]
From a technical standpoint I think this issue is resolved. There are data modeling issues that remain however, specifically with gene/protein conflation as well as with our use of species-non-specific Protein Ontology concepts in our KG. Both of these data modeling issues are still ongoing, and for that reason I think this issue should remain open for now.

**Comment by bill-baumgartner** [comment]
As was discussed during the mini-hackathon on 6/17, the Text Mining Provider will address the issue regarding our use of species-non-specific Protein Ontology concepts by releasing a new flavor of KG that will use human UniProt identifiers.

**Comment by nlharris** [comment]
Hi, I was told that this should be moved to Data Modeling. I assume that means there's a discussion point here to add to the next DM call agenda. Is this it?  @bill-baumgartner @sierra-moxon 
> There are data modeling issues that remain however, specifically with gene/protein conflation as well as with our use of species-non-specific Protein Ontology concepts in our KG.

**Comment by bill-baumgartner** [comment]
Thanks @nlharris, I believe this issue has been on the agenda for recent GM calls although I haven't attended them. @sierra-moxon or @mikebada can you confirm?

**Comment by mikebada** [comment]
This was at the end of the agenda for yesterday's Data Modeling call, but we didn't get to it. However, as Bill alluded to, following discussions with @cbizon and others, we're planning on providing one knowledge graph using taxon-nonspecific PRO classes for genes/gene products, which we will regard as the most reliable set of data, and at least one knowledge graph in which the taxon-nonspecific PRO classes are substituted with the PRO classes for the human orthologs. (I think the current plan is to provide one graph using HGNC IDs and another using UniProt IDs for queries using human genes and proteins, respectively; however, if/when gene/protein conflation is implemented, we may just provide one of these and let the conflator do some of the work.) We'll try to make clear through naming and documentation that the human-specific graphs are less reliable in that there's no basis that the assertions are indeed human-specific and that we're just using the human-specific orthologs of the taxon-nonspecific PRO entities to be able to answer queries using human genes and proteins. Happy to get feedback at some future DM call...

**Comment by vgardner-renci** [comment]
@mikebada request for follow up

**Comment by vgardner-renci** [comment]
@bill-baumgartner looking forward to update

**Comment by vgardner-renci** [comment]
Related to gene and protein conflation issue. Still in progress.

**Comment by vgardner-renci** [comment]
This query is no longer a part of the demo.
