### ISSUE TITLE
CHP query returning a 500 error

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/minihackathons#15]
```
qg = {
  "nodes": {
    "n0": {
      "categories": [
        "biolink:ChemicalSubstance"
      ],
      "name": "Chemical Substance"
    },
    "n1": {
      "name": "EGFR",
      "ids": ["NCBIGene:1956"]
    }
  },
  "edges": {
    "e0": {
      "subject": "n0",
      "object": "n1",
      "predicates": [
        "biolink:decreases_abundance_of",
        "biolink:decreases_activity_of",
        "biolink:decreases_expression_of",
        "biolink:decreases_synthesis_of",
        "biolink:increases_degradation_of",
        "biolink:disrupts",
        "biolink:negatively_regulates_entity_to_entity"
      ]
    }
  }
}
```

**Comment by tursynay** [comment]
Query:
qg = {
  "nodes": {
    "n0": {
      "categories": [
        "biolink:ChemicalSubstance"
      ],
      "name": "Chemical Substance"
    },
    "n1": {
      "name": "EGFR",
      "ids": ["NCBIGene:1956"]
    }
  },
  "edges": {
    "e0": {
      "subject": "n0",
      "object": "n1",
      "predicates": [
        "biolink:decreases_abundance_of",
        "biolink:decreases_activity_of",
        "biolink:decreases_expression_of",
        "biolink:decreases_synthesis_of",
        "biolink:increases_degradation_of",
        "biolink:disrupts",
        "biolink:negatively_regulates_entity_to_entity"
      ]
    }
  }
}

**Comment by GregHydeDartmouth** [comment]
Not gracefully handling malformed TRAPI queries. Exception is being caught appropriately by TRAPI model, but need to return blank message with appropriate error message.

![500 error on malformed trapi query](https://user-images.githubusercontent.com/60626258/119016242-b850b880-b967-11eb-8efd-bc7d6952f0ea.PNG)

**Comment by tursynay** [comment]
Looks like this issue is resolved
