### ISSUE TITLE
Textmining no results on Workflow A.5

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#153]
https://arax.ncats.io/?source=ARS&id=df3f226a-571a-4219-ba5e-a37b7040ee18

No predicates or categories, CURIE on subject

![image](https://user-images.githubusercontent.com/83781286/125841734-3567f00c-f0d0-40a9-aaca-7f00483fdc88.png)

**Comment by vgardner-renci** [comment]
```
{
  "callback": "http://0.0.0.0:8000/ars/api/messages/42f3b6c0-5303-4d1a-a2e3-5c066fd79c35",
  "max_results": 100,
  "message": {
    "query_graph": {
      "edges": {
        "e01": {
          "object": "n1",
          "subject": "n0"
        }
      },
      "nodes": {
        "n0": {
          "categories": [
            "biolink:Gene"
          ],
          "ids": [
            "NCBIGene:23221"
          ]
        },
        "n1": {}
      }
    }
  },
  "validation_result": {
    "message": "",
    "size": "0.90 kB",
    "status": "PASS",
    "version": "1.1.1"
  }
}

**Comment by vgardner-renci** [comment]
Sent query to ARS, Textmining results "Done / no results"

New PK; 0577463a-c78f-4835-9565-71e88f7c218e

![image](https://user-images.githubusercontent.com/83781286/127489023-decdba8c-f154-4cb8-8bf8-ee51b5fe2c29.png)


`{
  "logs": [
    {
      "code": null,
      "level": "DEBUG",
      "message": "BTE identified 2 QNodes from your query graph",
      "timestamp": "2021-07-29T12:05:19.439Z"
    },
    {
      "code": null,
      "level": "DEBUG",
      "message": "BTE identified 1 QEdges from your query graph",
      "timestamp": "2021-07-29T12:05:19.439Z"
    },
    {
      "code": null,
      "level": "DEBUG",
      "message": "BTE identified your query graph as a 1-depth query graph",
      "timestamp": "2021-07-29T12:05:19.439Z"
    },
    {
      "code": null,
      "level": "DEBUG",
      "message": "REDIS cache is  enabled.",
      "timestamp": "2021-07-29T12:05:20.646Z"
    },
    {
      "code": null,
      "level": "DEBUG",
      "message": "BTE is trying to find SmartAPI edges connecting from Gene to OrganismTaxon,BioticExposure,AdministrativeEntity,Agent,InformationContentEntity,Dataset,DatasetDistribution,DatasetVersion,DatasetSummary,ConfidenceLevel,EvidenceType,Publication,Book,BookChapter,Serial,Article,PhysicalEntity,MaterialSample,Activity,Procedure,Phenomenon,Device,PlanetaryEntity,EnvironmentalProcess,EnvironmentalExposure,EnvironmentalFeature,GeographicLocation,GeographicLocationAtTime,GeographicExposure,BiologicalEntity,MolecularEntity,ChemicalSubstance,Carbohydrate,ProcessedMaterial,FoodComponent,EnvironmentalFoodContaminant,FoodAdditive,Nutrient,Macronutrient,Micronutrient,Vitamin,Metabolite,ChemicalExposure,ComplexChemicalExposure,Drug,DrugExposure,DrugToGeneInteractionExposure,Food,GenomicEntity,Gene,Genome,Exon,Transcript,RnaProduct,RnaProductIsoform,NoncodingRnaProduct,MicroRna,SiRna,CodingSequence,Protein,ProteinIsoform,Genotype,Haplotype,SequenceVariant,Snv,ReagentTargetedGene,GenomicBackgroundExposure,GeneFamily,BiologicalProcessOrActivity,MolecularActivity,BiologicalProcess,Pathway,PhysiologicalProcess,Behavior,BehavioralExposure,SocioeconomicExposure,BehavioralOutcome,SocioeconomicOutcome,Death,MortalityOutcome,PathologicalProcess,PathologicalProcessExposure,PathologicalProcessOutcome,OrganismalEntity,LifeStage,IndividualOrganism,Case,PopulationOfIndividualOrganisms,StudyPopulation,Cohort,AnatomicalEntity,CellularComponent,Cell,GrossAnatomicalStructure,PathologicalAnatomicalStructure,PathologicalAnatomicalExposure,PathologicalAnatomicalOutcome,CellLine,DiseaseOrPhenotypicFeature,Disease,PhenotypicFeature,BehavioralFeature,ClinicalFinding,DiseaseOrPhenotypicFeatureExposure,DiseaseOrPhenotypicFeatureOutcome,EpidemiologicalOutcome,ClinicalEntity,ClinicalTrial,ClinicalIntervention,Hospitalization,HospitalizationOutcome,Treatment,NamedThing with predicate undefined",
      "timestamp": "2021-07-29T12:05:20.667Z"
    },
    {
      "code": null,
      "level": "WARNING",
      "message": "BTE didn't find any smartapi edges corresponding to e01",
      "timestamp": "2021-07-29T12:05:20.669Z"
    },
    {
      "code": null,
      "level": "WARNING",
      "message": "BTE didn't find any bte edges for this batch. Your query terminates.",
      "timestamp": "2021-07-29T12:05:20.669Z"
    }
  ],
  "message": {
    "knowledge_graph": {
      "edges": {},
      "nodes": {}
    },
    "query_graph": {
      "edges": {
        "e01": {
          "object": "n1",
          "subject": "n0",
          "id": "e01",
          "parentdivnum": 99999,
          "trapiversion": "1.1 (presumed)",
          "source": "n0",
          "target": "n1"
        }
      },
      "nodes": {
        "n0": {
          "categories": [
            "biolink:Gene"
          ],
          "ids": [
            "NCBIGene:23221"
          ],
          "is_set": false,
          "parentdivnum": 99999,
          "trapiversion": "1.1 (presumed)",
          "fulltextname": "n0",
          "id": "n0",
          "name": "NCBIGene:23221 (NCBIGene:23221) (NCBIGene:23221)"
        },
        "n1": {
          "is_set": false,
          "parentdivnum": 99999,
          "trapiversion": "1.1 (presumed)",
          "fulltextname": "n1",
          "id": "n1",
          "name": "(Any)"
        }
      }
    },
    "results": []
  },
  "validation_result": {
    "message": "",
    "n_edges": 0,
    "n_nodes": 0,
    "provenance_summary": {
      "n_sources": 0,
      "predicate_counts": {},
      "provenance_counts": {}
    },
    "size": "4 kB",
    "status": "PASS",
    "version": "1.1.1"
  },
  "araxui_provider": "ARS",
  "araxui_response": "bb34231f-bec5-4c68-9735-7c780fc1423c",
  "schema_version": "1.1 (presumed)"
}

**Comment by bill-baumgartner** [comment]
Zero results are expected as our KP does not handle NCBIGene identifiers. The Text Mining KP currently represents genes and gene products using species-non-specific Protein Ontology identifiers, but will also use human UniProt identifiers in an upcoming release. Closing for now.
