### ISSUE TITLE
Textmining error on Workflow A.7

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#158]
https://arax.ncats.io/?source=ARS&id=16cc3949-368d-485e-a7e6-c04b8ff81050

EGFR

![image](https://user-images.githubusercontent.com/83781286/125843996-380d3607-aa4b-4479-8947-9a56f104fcb3.png)

**Comment by vgardner-renci** [comment]
{
  "callback": "http://0.0.0.0:8000/ars/api/messages/288ce827-5bec-436e-a028-2a49064d0ccf",
  "max_results": 100,
  "message": {
    "query_graph": {
      "edges": {
        "e0": {
          "object": "n0",
          "predicates": [
            "biolink:related_to"
          ],
          "subject": "n1"
        }
      },
      "nodes": {
        "n0": {
          "categories": [
            "biolink:ChemicalSubstance"
          ],
          "name": "Chemical Substance"
        },
        "n1": {
          "ids": [
            "NCBIGene:1956"
          ],
          "name": "EGFR"
        }
      }
    }
  },
  "validation_result": {
    "message": "",
    "size": "1 kB",
    "status": "PASS",
    "version": "1.1.1"
  }
}

**Comment by vgardner-renci** [comment]
@bill-baumgartner rerunning the same ARAX a week later yields same "Error / NA" result on TextMining.

**Comment by vgardner-renci** [comment]
@bill-baumgartner Rerunning json to ARS shows Textmining "Error / NA" result

New PK: b3a87a3e-e852-4e52-88f3-56900aa46a26

**Comment by bill-baumgartner** [comment]
A.7 Is a multi-hop (two nodes with two edges) query which is not handled by our KP. Error is expected for this one. Our KP will only handle single-hop queries going forward so this issue can be closed (I think).

**Comment by tursynay** [comment]
Out of scope, closing.
