### ISSUE TITLE
Aragorn is not returning results 

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/minihackathons#16]
More context - query and results from the minihackathon on 05/20/2021:
Needs to be checked again after ARS registration is fixed.

Results: https://arax.ncats.io/?source=ARS&id=62fa9f13-a7e4-4971-9580-1fb87d5345e2 
Query:
qg = {
  "nodes": {
    "n0": {
      "categories": [
        "biolink:ChemicalSubstance"
      ],
      "name": "Chemical Substance"
    },
    "n1": {
      "name": "EGFR",
      "ids": ["NCBIGene:1956"]
    }
  },
  "edges": {
    "e0": {
      "subject": "n0",
      "object": "n1",
      "predicates": [
        "biolink:decreases_abundance_of",
        "biolink:decreases_activity_of",
        "biolink:decreases_expression_of",
        "biolink:decreases_synthesis_of",
        "biolink:increases_degradation_of",
        "biolink:disrupts",
        "biolink:negatively_regulates_entity_to_entity"
      ]
    }
  }
}

**Comment by cbizon** [comment]
Aragorn is now returning (ranked) results.  Checked via the dev-ars as well.
