### ISSUE TITLE
What is the correct predicate for the ingest of COHD into RTX?

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#165]
https://arax.ncats.io/?source=ARS&id=597d0a89-013c-47cd-a296-ada21af6fa15

![image](https://user-images.githubusercontent.com/83781286/126700492-52a8430e-3caf-488b-83f6-cc211b769d16.png)

![image](https://user-images.githubusercontent.com/83781286/126700316-4aa57c8b-19f4-4162-98e8-ab92a03cfcb6.png)

**Comment by vgardner-renci** [comment]
@dkoslicki @edeutsch @CaseyTa request for update

**Comment by edeutsch** [comment]
I do not know what this means or the answer to the question..

**Comment by dkoslicki** [comment]
@vgardner-renci I think this is something to ask the data modeling group. IIRC, COHD uses the `correlated_with` predicate, but since there are at least three distinct kinds of edges (paired concept frequency, log observed/expected, and chi square p-value), we thought it best to be more specific.

**Comment by CaseyTa** [comment]
What is the timeline for resolving this issue? 

If this is for immediate ingest of COHD, I would suggest working with the `correlated_with` predicate. Currently, COHD decides if there is an edge between a pair of concepts based on significance of the log observed/expected metric. The other metrics (chi-square, relative frequency) are currently tagging along as additional edge attributes on this edge. 

There is more discussion on how to better model the "knowledge" from the clinical KPs in https://github.com/NCATSTranslator/minihackathons/issues/47. In the near future, we will adopt the temporary predicate `has real world evidence of association with`, which will replace the `correlated with` predicate while maintaining the same behavior described above. Distinct predicates to differentiate the various metrics available in COHD and other clinical KPs have not yet been established.

**Comment by tursynay** [comment]
Leave it until what is showing up in RTX is the right predicate

**Comment by tursynay** [comment]
@edeutsch will follow up

**Comment by vgardner-renci** [comment]
@edeutsch request for update

**Comment by tursynay** [comment]
@vgardner-renci to check in with Eric

**Comment by vgardner-renci** [comment]
@edeutsch can you comment?

**Comment by amykglen** [comment]
Ok, we now use the predicate `biolink:has_real_world_evidence_of_association_with` for all COHD edges - example: https://arax.ncats.io/?r=23658

So I think this issue is resolved.
