### ISSUE TITLE
Improving no results on Workflow C.3

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#172]
https://arax.ncats.io/?source=ARS&id=c34d54c8-d9a5-4aca-99ef-967f158b4125

![image](https://user-images.githubusercontent.com/83781286/127532585-e7b21263-c24a-4054-b2cc-ab8b5c7b4eac.png)

**Comment by brettasmi** [comment]
We don't have this edge. Is this something that's expected to come from multi-omics?

**Comment by rtroper** [comment]
> We don't have this edge. Is this something that's expected to come from multi-omics?

We're looking for results from any KPs/ARAs. So far, this query has been a challenge. It has two specified nodes and we're looking for any type of relation between them. Even if edges exist for the two specified nodes, I'm not sure many KPs/ARAs are handling this case. Where we get results, it appears that the responding KP/ARA is only fixing one of the nodes and ignoring the other.

**Comment by jenndoug** [comment]
@suihuang-ISB Sui, re Ryan's response to Brett: out of scope for Improving?  We can discuss next team meeting - next Weds.  Jenn

**Comment by vgardner-renci** [comment]
@jenndoug update on this issue?

**Comment by rtroper** [comment]
Note, as described [here](https://github.com/NCATSTranslator/minihackathons/issues/173#issuecomment-905559528), we plan to drop query C.3 from workflow C and rely, instead, on overlay edges for research evidence. However, if we (Translator) are interested in being able to answer these kinds of queries, we may want to keep this open. But, it's no longer needed for workflow C.
