### ISSUE TITLE
How do we add additional constraints into the query such as FDA approval & application method

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/minihackathons#19]
How do we add additional constraints into the query such as FDA approval application method. 

Look into EGFR  downregulate at the next mini-hackathon

(more details needed for this issue)

**Comment by vgardner-renci** [comment]
Handed over to DM committee. Will resolve with next BL model release.

**Comment by tursynay** [comment]
Should be resolved today

**Comment by tursynay** [comment]
Closing the issue, see https://github.com/NCATSTranslator/minihackathons/issues/164 and https://github.com/NCATSTranslator/minihackathons/issues/163
