### ISSUE TITLE
Improving ARS error on Workflow A.2

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#196]
https://arax.ncats.io/?source=ARS&id=2a6a79e3-5662-4961-9375-79c599a2d954

![image](https://user-images.githubusercontent.com/83781286/129218771-dee4424b-4601-4a2e-832d-53f8489ec56a.png)

```
{
  "description": "imProving Agent could not find query nodes of category ['biolink:SmallMolecule']; returning empty message...",
  "message": {},
  "status": "Query unprocessable",
  "validation_result": {
    "message": "",
    "size": "0.54 kB",
    "status": "PASS",
    "version": "1.1.1"
  },
  "araxui_provider": "ARS",
  "araxui_response": "d7ba9945-e177-44eb-ad75-c852738fd580"
}

**Comment by brettasmi** [comment]
I'm not able to recreate this error and I think there may be an error in this query: 
https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowA/A.2_RHOBTB2_twohop.json

I think it's missing the closing `}` for edge `e01`

When I add it and query the improving agent directly, it seems to work.

**Comment by vgardner-renci** [comment]
https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowA/A.2_RHOBTB2_twohop.json

**Comment by jenndoug** [comment]
@vgardner-renci Close?
