### ISSUE TITLE
Molecular KP is not returning results on A.8

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/minihackathons#20]
Hi Vlado, 

Chris B ran this query during the last mini-hackathon, Molecular KP did not return results. 
Here is the link from ARAX with results of that query run: https://arax.ncats.io/?source=ARS&id=90080f07-808c-47db-a042-21a9ce6f4281 

here is the query itself, please take a look. Chris B and Anne would like to revisit the query during the next mini-hackathon which is scheduled for next week (June 3). Would you be able to get back to this issue before that time?

 qg = {
  "nodes": {
    "n0": {
      "categories": [
        "biolink:ChemicalSubstance"
      ],
      "name": "Chemical Substance"
    },
    "n1": {
      "name": "EGFR",
      "ids": ["NCBIGene:1956"]
    }
  },
  "edges": {
    "e0": {
      "subject": "n0",
      "object": "n1",
      "predicates": [
        "biolink:decreases_abundance_of",
        "biolink:decreases_activity_of",
        "biolink:decreases_expression_of",
        "biolink:decreases_synthesis_of",
        "biolink:increases_degradation_of",
        "biolink:disrupts",
        "biolink:negatively_regulates_entity_to_entity"
      ]
    }
  }
}

**Comment by vdancik** [comment]
Listed predicates are not supported by MolePro. Changing predicate to "biolink:affected_by" yields results:

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": [
                        "biolink:ChemicalSubstance"
                    ],
                    "name": "Chemical Substance"
                },
                "n1": {
                    "name": "EGFR",
                    "ids": [
                        "NCBIGene:1956"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n1",
                    "object": "n0",
                    "predicates": ["biolink:affected_by"]
                }
            }
        }
    }
}
```

**Comment by cbizon** [comment]
@vdancik does MolePro have any more specific predicates?   Anything that distinguishes up from down ?

**Comment by cbizon** [comment]
OK, then if it's ok, I think we should leave this one open, as we anticipate that molepro will add such predicates.

**Comment by vgardner-renci** [comment]
@vdancik request for update

**Comment by vgardner-renci** [comment]
Vlado indicates, Waiting for Chemical WG to implement changes. Mid August

**Comment by tursynay** [comment]
Those are predicates that we don't have in MolePro, once these are done, it will be implemented

**Comment by vgardner-renci** [comment]
@vdancik Mid-August check-in.

**Comment by vdancik** [comment]
ChemInfo WG finished harmonizing predicates this week, waiting for Biolink to incorporate the proposed changes.

**Comment by vdancik** [comment]
MolePro TRAPI version 1.2 now handles this query.

**Comment by vgardner-renci** [comment]
@vdancik Running the A.8 query thru the ARAX User Interface still shows no results. 


```{
  "message": {
    "knowledge_graph": {
      "edges": {},
      "nodes": {}
    },
    "query_graph": {
      "edges": {
        "e0": {
          "object": "n1",
          "predicates": [
            "biolink:decreases_abundance_of",
            "biolink:decreases_activity_of",
            "biolink:decreases_expression_of",
            "biolink:decreases_synthesis_of",
            "biolink:increases_degradation_of",
            "biolink:disrupts",
            "biolink:entity_negatively_regulates_entity"
          ],
          "subject": "n0"
        }
      },
      "nodes": {
        "n0": {
          "categories": [
            "biolink:SmallMolecule"
          ],
          "is_set": false
        },
        "n1": {
          "ids": [
            "NCBIGene:1956"
          ],
          "is_set": false
        }
      }
    },
    "results": []
  },
  "validation_result": {
    "message": "",
    "n_edges": 0,
    "n_nodes": 0,
    "provenance_summary": {
      "n_sources": 0,
      "predicate_counts": {},
      "provenance_counts": {}
    },
    "size": "1 kB",
    "status": "PASS",
    "version": "1.1.1"
  },
  "araxui_provider": "ARS",
  "araxui_response": "6868e207-f028-4541-a814-07e92f2ac29b"
}

**Comment by tursynay** [comment]
This is more of an ARS question. Works for MolePro's version that calls 1.2.

**Comment by vgardner-renci** [comment]
Post Trapi 1.2

![image](https://user-images.githubusercontent.com/83781286/132692536-48cba6b4-c666-46f9-bb1b-4af20621be0a.png)

https://arax.ncats.io/?source=ARS&id=fb3c0979-a809-4dc8-a064-931961be9717

https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowA/A.8_EGFR_simple.json

**Comment by vgardner-renci** [comment]
Molepro returning results

https://arax.ncats.io/?source=ARS&id=718eb8c4-5fbc-475c-a5f4-34ff390f28fe
