### ISSUE TITLE
Add edge to workflow A

### ISSUE THREAD

**Issue by GregHydeDartmouth** [NCATSTranslator/minihackathons#217]
Connections Hypothesis Provider has the ability to answer gene to gene relationships that I think would be helpful for workflow A. I brought this up at the last hackathon and it seem as though ARAs were interested in using this edge for the workflow A queries. This would require the addition of the predicate "biolink:genetically_interacts_with" on the gene to gene edges and includes [workflow A.1](https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowA/A.1_RHOBTB2.json) and [workflow A.2](https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowA/A.2_RHOBTB2_twohop.json).

Info for how this edge is computed: https://di2ag.github.io/chp/chp_documentation#chp-two-hop-contribution-analysis

**Comment by cbizon** [comment]
I added the edge to WF A.2.   I'm not sure about adding to A.1 b/c that query has a directional aspect that the genetically interacts with predicate does not.
