### ISSUE TITLE
Aragorn not pulling COHD results in D.3 query

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#229]

**Comment by vgardner-renci** [comment]
https://arax.ncats.io/?source=ARS&id=5eb60469-59d7-442c-87eb-8a622363313e

**Comment by cbizon** [comment]
This appears to be because we are sending a list of categories including ['biolink:SmallMolecule', 'biolink:ChemicalSubstance'], but cohd doesn't like that latter one and throws a 400.     

I think ChemicalSubstance is still valid as an alias, but maybe we should stop sending it.

**Comment by vgardner-renci** [comment]
@cbizon dependent issue closed. Is this issue resolved for Aragorn?

**Comment by cbizon** [comment]
Yes
