### ISSUE TITLE
ARAX results "(S)-2-amino-4-(2-formamidophenyl)-4-oxobutanoic acid" when "kynurenine" is expected in D.4

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#231]

**Comment by vgardner-renci** [comment]
https://arax.ncats.io/?source=ARS&id=f2886569-5ebb-49c3-aa35-a047d40f6d9b

https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowD/D.4_tryptophan-kynurenine-with-curie.json

![image](https://user-images.githubusercontent.com/83781286/131883982-bec343f6-b715-432e-992f-2a5b63380e05.png)

**Comment by saramsey** [comment]
we are working this issue in https://github.com/RTXteam/RTX/issues/1622

**Comment by edeutsch** [comment]
This is now fixed. okay to close?

**Comment by vgardner-renci** [comment]
![image](https://user-images.githubusercontent.com/83781286/133613155-17e2e678-6178-4068-8a40-93b34bd97995.png)
