### ISSUE TITLE
Aragorn results in one edge being linked to self sub-class edge in D.6

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#233]
https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowD/D.6_metformin-ferritin.json

**Comment by vgardner-renci** [comment]
https://arax.ncats.io/?source=ARS&id=63f1d251-0d09-42a5-9b42-f7e8e75eb690

**Comment by vgardner-renci** [comment]
![image](https://user-images.githubusercontent.com/83781286/131890474-f12cfcef-5095-4312-9904-641041785667.png)

**Comment by vgardner-renci** [comment]
@cbizon dependent issue closed. Is this issue resolved in Aragorn?

**Comment by cbizon** [comment]
Yes
