### ISSUE TITLE
DILI dataset authorization API issue

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/minihackathons#25]
NOTE: DILI dataset requires authorization key to be exposed in the query, there is a caveat that the dataset is not exposed outside of Translator until they (org) have published something. No timelines on this are known. To be discussed at the next Architecture call. Kara to discuss a potential solution at the meeting on June 8.

**Comment by karafecho** [comment]
Comment:  The DILI dataset is derived from a 20-year longitudinal study conducted by the international DILI Network (DILIN). DILIN leadership have not yet published any of the findings, so they've requested that we restrict access to the Translator consortium until they publish their work (or we do). FWIW, I view this as an interesting use case for Translator, albeit a challenging one.

**Comment by karafecho** [comment]
Exposures Provider will explore alternative approaches such as placing restrictions on incoming IP addresses and/or requiring an initial one-time registration.

**Comment by vgardner-renci** [comment]
@karafecho please comment and if appropriate please close issue.

**Comment by karafecho** [comment]
@vgardner-renci : Please see below the consortium-wide notice that I distributed on 6/10/2021. Perhaps you can check with those PIs who have not signed the agreement (note that this includes Stan, Ashok, Alex, and [ideally] a representative from Link Brokers) and clarify whether (1) they plan to sign but simply haven't had time/forgot OR (2) they are unwilling to sign. Thanks!

Dear Translator Consortium:

As you likely are aware, Exposures Provider has contributed a unique clinical resource to the Translator ecosystem, namely, a drug-induced liver injury (DILI) dataset, exposed via an ICEES+ instance. The DILI dataset is derived from a 20-year study conducted by the international DILI Network. Paul Watkins, MD, whom many of you have met, serves as the UNC PI. We are grateful to have access to this valuable resource.
The DLI Network has not yet published their findings on this particular dataset. As such, they have kindly requested that we restrict access to the Translator Consortium. Originally, we planned to implement this requirement by way of an authorization key, and we deployed an ICEES+ instance with an API key in place. However, after discussions with Consortium members and NCATS, we realized that this solution will not be supported by the Translator architecture.

Upon further discussion with Paul, I am pleased to report that we are no longer requiring an authorization key, and we have deployed a new key-free instance of the ICEES+ DILI API. Please note that we are asking Translator team members to review the terms and conditions of service. These are returned in all ICEES+ DILI responses. (The ICEES+ asthma instance returns similar terms and conditions.) We are also asking Translator PIs to review the statement here and agree to submit any secondary products (e.g., journal articles) related to the ICEES+ DILI instance to both the Translator Publications Committee and the DILI Network Publications Committee for review prior to publication and/or public release.

Thank you for your time and understanding. We believe that the solution we've adopted for the ICEES+ DILI API will help to protect the investment of the DILI Network, while also promoting the goals of the Translator program.

Best,

Kara Fecho, on behalf of Exposures Provider

**Comment by vgardner-renci** [comment]
@karafecho - I'm following up with Tyler about a signer from Link Brokers. Marian is following up with the RENCI folks.

**Comment by karafecho** [comment]
Thanks, @vgardner-renci . Is anyone following up with any other PIs? I think that would be helpful.

**Comment by vgardner-renci** [comment]
OK to close.
