### ISSUE TITLE
KP should be able to handle multihop query in this case

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/minihackathons#26]
@marcdubybroad, this is just to follow up with you later, I know you already took it on during the mini-hack meeting: https://arax.ncats.io/?source=ARS&id=37aa56a7-a6de-44eb-a15e-13502899410c

One suspicion is the issue is occurring because of DILI dataset API authorization issue discussed during the meeting

**Comment by marcdubybroad** [comment]
Json:
{
  "edges": {
    "e0": {
      "object": "n1",
      "predicates": [
        "biolink:correlated_with"
      ],
      "subject": "n0"
    },
    "e1": {
      "object": "n2",
      "predicates": [
        "biolink:condition_associated_with_gene"
      ],
      "subject": "n1"
    },
    "e2": {
      "object": "n3",
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n2"
    }
  },
  "nodes": {
    "n0": {
      "ids": [
        "MONDO:0005359"
      ],
      "name": "drug-induced liver injury"
    },
    "n1": {
      "categories": [
        "biolink:DiseaseOrPhenotypicFeature"
      ],
      "name": "Disease Or Phenotypic Feature"
    },
    "n2": {
      "categories": [
        "biolink:Gene"
      ],
      "name": "Gene"
    },
    "n3": {
      "categories": [
        "biolink:ChemicalSubstance"
      ],
      "name": "Chemical Substance"
    }
  }
}

**Comment by marcdubybroad** [comment]
Fixed; Genetics KP will now return 501 error code as opposed to returning partial erroneous results. This will indicate the KP does not support multi hop queries.

**Comment by tursynay** [comment]
Going to close this as completed then. Thanks @marcdubybroad.
