### ISSUE TITLE
Aragorn should be returning results for this but is not

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/minihackathons#27]
https://arax.ncats.io/?source=ARS&id=7c8d4771-cbdb-4e71-84bc-33fb65e068cb

**Comment by cbizon** [comment]
This is a mismatch between Aragorn and COHD in how /meta_knowledge_graph should be implemented: https://github.com/WengLab-InformaticsResearch/cohd_api/issues/30

**Comment by cbizon** [comment]
COHD has modified its metakg - now we need to rebuild strider's KP registry.

**Comment by PhillipsOwen** [comment]
i rebuilt the kp-registry and strider is now picking up and using the COHD api.

unfortunately COHD is throwing the error "COHD TRAPI requires at least one node to have an ID". the qgraph json is included here for reference.

[COHD_query.json.txt](https://github.com/NCATSTranslator/minihackathons/files/6608764/COHD_query.json.txt)

**Comment by cbizon** [comment]
Can you make an issue on the cohd github site (link above)?

**Comment by PhillipsOwen** [comment]
of course. and i did...

**Comment by tursynay** [comment]
Just including the issue that @PhillipsOwen opened per @cbizon above: https://github.com/WengLab-InformaticsResearch/cohd_api/issues/33

**Comment by CaseyTa** [comment]
Thanks for bringing this to my attention, @PhillipsOwen and @cbizon. I just tested, and the specific issue mentioned doesn't seem to be a problem any more. However, COHD is currently throwing an error message about not supporting constraints even though the QNode has a null constraint. I created a new issue for this and should have it fixed soon. https://github.com/WengLab-InformaticsResearch/cohd_api/issues/35

**Comment by CaseyTa** [comment]
Constraint issue now also resolved.

**Comment by vgardner-renci** [comment]
@PhillipsOwen double check the query to determine if its returning results now

**Comment by PhillipsOwen** [comment]
COHD is returning data. however it contains non-compliant TRAPI. 

i added specifics to the cohd repo issue (https://github.com/WengLab-InformaticsResearch/cohd_api/issues/35)

**Comment by CaseyTa** [comment]
@PhillipsOwen I also responded in the [COHD API issue 35](https://github.com/WengLab-InformaticsResearch/cohd_api/issues/35), but I believe the response from COHD is compliant with TRAPI 1.1. The `description` property is defined for the `Attribute` object here: 
https://github.com/NCATSTranslator/ReasonerAPI/blob/42a9d073a92d7aaba0ddf080e461d2da088003fc/TranslatorReasonerAPI.yaml#L604

**Comment by cbizon** [comment]
Yep, looks like this is a validation problem on our end rather than a compliance issue on COHD's.

**Comment by vgardner-renci** [comment]
@cbizon request for update on Strider validation issue (was the fix deployed)

**Comment by cbizon** [comment]
The query for reference: 
```
{
  "edges": {
    "e0": {
      "object": "n1",
      "predicates": [
        "biolink:correlated_with"
      ],
      "subject": "n0"
    }
  },
  "nodes": {
    "n0": {
      "ids": [
        "SNOMEDCT:197358007"
      ],
      "is_set": false,
      "name": "drug-induced liver injury"
    },
    "n1": {
      "categories": [
        "biolink:DiseaseOrPhenotypicFeature"
      ],
      "is_set": false,
      "name": "Disease Or Phenotypic Feature"
    }
  }
}
```

**Comment by cbizon** [comment]
Aragorn is now returning results from COHD
