### ISSUE TITLE
TRAPI team to look into this query result

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/minihackathons#28]
Here is the snomed query: https://arax.ncats.io/?source=ARS&id=7c8d4771-cbdb-4e71-84bc-33fb65e068cb
Eric D will look into this
Are these filtered results or not.

**Comment by vgardner-renci** [comment]
@edeutsch any response to this issue?

**Comment by edeutsch** [comment]
Hi @vgardner-renci @tursynay the answer is that we have a setting that filters the COHD responses. The default filtering at 99 percentile only keeps the top 12 results in this case and the others don't pass the filter and are dropped.

We are reviewing internally how to adjust this so we are not being so aggressive with our filtering.

**Comment by vgardner-renci** [comment]
Fix is in progress per Eric.

**Comment by vgardner-renci** [comment]
Fix is in
