### ISSUE TITLE
Workflow C.1a timeout preventing results from clinical risk KP

### ISSUE THREAD

**Issue by rtroper** [NCATSTranslator/minihackathons#289]
Submitting [workflow query C.1a](https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowC/C.1a_SmallMolecule_real_world_evidence_MultSclerosis.json) directly to BTE (https://api.bte.ncats.io/v1/query) or the clinical risk KP endpoint (https://api.bte.ncats.io/v1/smartapi/d86a24f6027ffe778f84ba10a7a1861a/query) yields results in about 5 seconds. When submitted to the ARS, expected results from the clinical risk KP are returned via BTE, but not ARAX.

For workflow C, we're interested in the ranked results from clinical KPs that ARAX provides. However, a timeout of 30 seconds is imposed and this does not end up being enough to get the results back from the clinical risk KP.

Below, is what we see when submitting the query directly to ARAX. I noticed in the status description (while waiting for results) that the query is submitted to the KPs/ARAs with 18 curies (presumably as a result of expanding the curie to synonyms). Perhaps the delay in getting results back within 30 seconds is due to this batch query. In any case, it seems our KP needs more time to get results back to ARAX. @dkoslicki @edeutsch - Would it be possible to have the timeout cutoff increased? Or would another solution be better?

![image](https://user-images.githubusercontent.com/18222763/134412666-79214d68-d6cd-47af-bcfd-66c3a12eba6c.png)

**Comment by dkoslicki** [comment]
@rtroper you can follow the progress of this issue here: https://github.com/RTXteam/RTX/issues/1670

**Comment by rtroper** [comment]
> @rtroper you can follow the progress of this issue here: [RTXteam/RTX#1670](https://github.com/RTXteam/RTX/issues/1670)

Yeah, definitely. Thanks for adding that.

**Comment by rtroper** [comment]
Just noting an update on this: https://github.com/RTXteam/RTX/issues/1674#issuecomment-926348287. This has improved response time for the clinical risk KP from >30 seconds to ~10 seconds. Once the change has been pushed to production, we should be able to close this issue here.

**Comment by edeutsch** [comment]
New (and all latest) code is now in production. Queries are definitely faster:
![image](https://user-images.githubusercontent.com/12707718/134748756-00699278-e0a6-4326-bb55-823ecf41e886.png)

Mechanism to increase query time is also in place on production.
Closing.
