### ISSUE TITLE
Open Predict is not returning results for this query

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/minihackathons#29]
https://arax.ncats.io/?source=ARS&id=7c8d4771-cbdb-4e71-84bc-33fb65e068cb

**Comment by CaseyTa** [comment]
@arifx OpenPredict is encountering a 500 internal server error with this query

**Comment by micheldumontier** [comment]
@vemonet

**Comment by vemonet** [comment]
Only the ID is not enough to reproduce the query and fix it

![Screenshot from 2021-06-25 16-57-17](https://user-images.githubusercontent.com/3778439/123443841-8d94f800-d5d6-11eb-9928-b3282fde3c2e.png)


Please send the query or a link to it

**Comment by CaseyTa** [comment]
@vemonet, looks like this is the query that was used: 
```
{
  "message": {
    "query_graph": {
      "edges": {
        "e0": {
          "object": "n1",
          "predicates": [
            "biolink:correlated_with"
          ],
          "subject": "n0"
        }
      },
      "nodes": {
        "n0": {
          "ids": [
            "SNOMEDCT:197358007"
          ],
          "name": "drug-induced liver injury"
        },
        "n1": {
          "categories": [
            "biolink:DiseaseOrPhenotypicFeature"
          ],
          "name": "Disease Or Phenotypic Feature"
        }
      }
    }
  }
}
```

We don't expect OpenPredict to return any results for the `biolink:correlated_with` predicate, but it's currently throwing a 500 internal server error. 
```
{
  "detail": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.",
  "status": 500,
  "title": "Internal Server Error",
  "type": "about:blank"
}
```
