### ISSUE TITLE
BTE should return results for this query but it does not

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/minihackathons#30]
https://arax.ncats.io/?source=ARS&id=7c8d4771-cbdb-4e71-84bc-33fb65e068cb

**Comment by andrewsu** [comment]
TRAPI query:
```
{
  "message": {
    "query_graph": {
      "edges": {
        "e0": {
          "object": "n1",
          "predicates": [
            "biolink:correlated_with"
          ],
          "subject": "n0"
        }
      },
      "nodes": {
        "n0": {
          "ids": [
            "SNOMEDCT:197358007"
          ],
          "name": "drug-induced liver injury"
        },
        "n1": {
          "categories": [
            "biolink:DiseaseOrPhenotypicFeature"
          ],
          "name": "Disease Or Phenotypic Feature"
        }
      }
    }
  }
}
```

**Comment by andrewsu** [comment]
based on changes in the BTE registration made by Mark, BTE now returns a valid TRAPI response (different than the above results last week), but we will still look into why we get zero results.
![image](https://user-images.githubusercontent.com/2635409/121289128-5a91fb00-c899-11eb-95f7-1a5db1e2da1b.png)

**Comment by colleenXu** [comment]
@andrewsu Should Clinical Risk KP API be called in this step?

Looking at the Clinical Risk KP API:

- the predicates are currently related_to or associated_with_risk_for (not correlated_with) 
- I don't find this SNOMEDCT ID in the resource: see https://biothings.ncats.io/clinical_risk_kp/query?q=subject.SNOMEDCT:"SNOMEDCT:197358007"
- Looking [here](https://browser.ihtsdotools.org/?), I found the ID's label to be: Toxic liver disease with acute hepatitis (disorder) 
- Using the browser linked above, I am looking into other IDs. However, I don't find the following IDs in Clinical Risk KP API (these are disorder semantic type):
  - Drug-induced disorder of liver, SNOMEDCT:427399008
  - Drug-induced cirrhosis of liver, SNOMEDCT:425413006
  - Drug-induced liver hypersensitivity disease, SNOMEDCT:735456000
  - Drug-induced hepatitis, SNOMEDCT:235876009
