### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by nlharris** [NCATSTranslator/minihackathons#302]
This workflow would benefit from a README that explains what the workflow is, like Workflows B-D have (e.g., https://github.com/NCATSTranslator/minihackathons/tree/main/2021-12_demo/workflowD)

If the description of Workflow A exists elsewhere, the README could just point to that.

**Comment by vgardner-renci** [comment]
@nlharris I've assigned to Chris. He's aware.

**Comment by nlharris** [comment]
probably moot at this point? close as not planned?
