### ISSUE TITLE
ARAX is returning errors on this two-hop query

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/minihackathons#32]
https://arax.ncats.io/?source=ARS&id=b781412a-69df-4366-98ac-9e889e10a538 

arax was returning an error on the two hop query

**Comment by dkoslicki** [comment]
This is the associated query, correct?
```
{
  "edges": {
    "e0": {
      "object": "n1",
      "predicates": [
        "biolink:correlated_with"
      ],
      "subject": "n0"
    },
    "e1": {
      "object": "n2",
      "predicates": [
        "biolink:condition_associated_with_gene"
      ],
      "subject": "n1"
    }
  },
  "nodes": {
    "n0": {
      "ids": [
        "SNOMEDCT:197358007"
      ],
      "name": "drug-induced liver injury"
    },
    "n1": {
      "categories": [
        "biolink:DiseaseOrPhenotypicFeature"
      ],
      "name": "Disease Or Phenotypic Feature"
    },
    "n2": {
      "categories": [
        "biolink:Gene"
      ],
      "name": "Gene"
    }
  }
}
```
Don't know why the TRAPI validator is complaining, but both RTX-KG2 and GeneticsKP can't fulfill the second hop (i.e. no results found).

**Comment by dkoslicki** [comment]
This has now been fixed. Turns out the second hop can't be fulfilled by any of the KPs that can handle such an edge. I can't close this issue, so @tursynay feel free to do so.

**Comment by dkoslicki** [comment]
@vgardner-renci This has been fixed a few days ago and now is returning a “no paths found” for edge e1. Can this issue be closed?

**Comment by vgardner-renci** [comment]
Ready to close. Thanks @dkoslicki
