### ISSUE TITLE
ARA Operations and Workflow issues

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#38]

**Comment by rtroper** [comment]
### Summary
To add some detail to this issue, Workflow C Query 2 (see TRAPI 1.1 query, below, and issue #34) does not currently return results from ARAs (see issue #40). There are two unconstrained nodes (see n0 and n3, below), which could be part of the problem. If so, this argues in favor of making operations a priority for the December demo. Operations such as those implemented by ARAX (and accessible using their DSL) could provide additional reasoning logic to make such queries more tractable. As an example, the ARAX DSL query at the bottom of this comment gives results for the TRAPI query immediately below.

### TRAPI 1.1
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:Gene"]
                },
                "n1": {
                    "ids": ["CHEBI:45783"],
                    "categories": ["biolink:ChemicalSubstance"]
                },
                "n2": {
                    "ids": ["MONDO:0005301"],
                    "categories": ["biolink:Disease"]
                },
                "n3": {
                    "categories": ["biolink:ChemicalSubstance"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:related_to"]
                },
                "e02": {
                    "subject": "n0",
                    "object": "n2",
                    "predicates": ["biolink:related_to"]
                },
                "e03": {
                    "subject": "n0",
                    "object": "n3",
                    "predicates": ["biolink:related_to"]
                }
            }
        }
    }
}
```

### ARAX DSL Query
```
add_qnode(key=n0, categories=biolink:Gene, is_set=True)
add_qnode(key=n1, ids=CHEBI:45783, categories=biolink:ChemicalSubstance)
add_qedge(key=e01, subject=n0, object=n1, predicates=biolink:related_to)
add_qnode(key=n2, ids=MONDO:0005301, categories=biolink:Disease)
add_qedge(key=e02, subject=n0, object=n2, predicates=biolink:related_to)
add_qnode(key=n3, categories=biolink:ChemicalSubstance)
add_qedge(key=e03, subject=n0, object=n3, predicates=biolink:related_to)
expand()
overlay(action=compute_jaccard,start_node_key=n1,intermediate_node_key=n0,end_node_key=n3,virtual_relation_label=J1)
overlay(action=compute_jaccard,start_node_key=n2,intermediate_node_key=n0,end_node_key=n3,virtual_relation_label=J2)
overlay(action=compute_ngd,default_value=inf,virtual_relation_label=N1,subject_qnode_key=n3,object_qnode_key=n2)
overlay(action=compute_ngd,default_value=inf,virtual_relation_label=N2,subject_qnode_key=n3,object_qnode_key=n1)
resultify()
filter_results(action=limit_number_of_results, max_results=50, prune_kg=true)
```

**Comment by dkoslicki** [comment]
@rtroper Would you like to attend the operations and workflow working group that meets on Tuesdays at 4pm ET? You insight about which operations to prioritize would be helpful. If so, @tursynay , can you send the Zoom invite to Ryan?

Side note: we do have [compute_ngd](https://github.com/NCATSTranslator/OperationsAndWorkflows/blob/main/operations/overlay_compute_ngd.yml) and [compute_jaccard](https://github.com/NCATSTranslator/OperationsAndWorkflows/blob/main/operations/overlay_compute_jaccard.yml) implemented in the [O/W repo](https://github.com/NCATSTranslator/OperationsAndWorkflows) and a [workflow runner](https://github.com/NCATSTranslator/workflow-runner) to execute the operations. Some ARAs have implemented and advertised which operations they can do in their [OpenAPI schema](https://arax.ncats.io/api/arax/v1.1/openapi.json). So the only technical missing component is having the ARS actually ask for operations in TRAPI ala [this TRAPI PR](https://github.com/NCATSTranslator/ReasonerAPI/pull/200).

**Comment by rtroper** [comment]
> @rtroper Would you like to attend the operations and workflow working group that meets on Tuesdays at 4pm ET? You insight about which operations to prioritize would be helpful. If so, @tursynay , can you send the Zoom invite to Ryan?

I do have that on my schedule. I've dropped in periodically, but yeah, it would make sense for me to start attending this more often.

**Comment by karafecho** [comment]
+1 to _"Operations such as those implemented by ARAX (and accessible using their DSL) could provide additional reasoning logic to make such queries more tractable."_

Of note, I think that most/all of the ARAs have rather sophisticated operations to support reasoning. It would be great to be able to leverage those capabilities via TRAPI queries.

Just my two cents...

**Comment by vgardner-renci** [comment]
Will resolve in July deployment

**Comment by vgardner-renci** [comment]
@rtroper and @karafecho fill in operations for your respective workflows

**Comment by rtroper** [comment]
For now, the following are the essential ones for workflow C: expand, overlay, filter

**Comment by dkoslicki** [comment]
@rtroper and `sort`, correct?

**Comment by rtroper** [comment]
> @rtroper and `sort`, correct?

Yes, thanks for pointing that out. We'll definitely want sort.

**Comment by karafecho** [comment]
@dkoslicki : For Workflow B, I think we'd also like all four operations (expand, overlay, filter, sort).

**Comment by dkoslicki** [comment]
Great, thanks @karafecho. There are PR's for these in the [O/W repo](https://github.com/NCATSTranslator/OperationsAndWorkflows).

**Comment by tursynay** [comment]
There are PRs for all of them in the Ops and W repo, and this will be resolved once all of these PRs are merged.

**Comment by vgardner-renci** [comment]
@dkoslicki can you verify that the PR's related to these operations have been merged?

**Comment by dkoslicki** [comment]
@vgardner-renci All have been merged except for `sort`, which @finnagin is working on

**Comment by vgardner-renci** [comment]
https://github.com/NCATSTranslator/OperationsAndWorkflows/pull/47 for sort is merged. 

Closing.
