### ISSUE TITLE
MolePro unable to digest multihop queries

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#39]

**Comment by vdancik** [comment]
MolePro as a KP only supports one-hop queries.

**Comment by vgardner-renci** [comment]
@vdancik will this be fixed?

**Comment by codewarrior2000** [comment]
> @vdancik will this be fixed?

@vgardner-renci  For now, Vlado's statement of June 14th (see above: "MolePro as a KP only supports one-hop queries." ) is still true.

**Comment by cbizon** [comment]
OK, sounds like we can close this one as "out of scope"
