### ISSUE TITLE
Multiple ARAs return errors for Workflow C Query 2

### ISSUE THREAD

**Issue by rtroper** [NCATSTranslator/minihackathons#40]
### Summary
Query 2 from workflow C (see #34) returns errors from multiple ARAs.
Submitted to: https://ars-dev.transltr.io/ars/api/submit
ARS pk: ec03a9bb-af05-4bf3-a57d-f196c02c858b

### Screenshot of Results
![image](https://user-images.githubusercontent.com/18222763/122094475-133bcb00-cdc1-11eb-8c1a-ebb105ab6077.png)

### TRAPI 1.1
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:Gene"]
                },
                "n1": {
                    "ids": ["CHEBI:45783"],
                    "categories": ["biolink:ChemicalSubstance"]
                },
                "n2": {
                    "ids": ["MONDO:0005301"],
                    "categories": ["biolink:Disease"]
                },
                "n3": {
                    "categories": ["biolink:ChemicalSubstance"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:related_to"]
                },
                "e02": {
                    "subject": "n0",
                    "object": "n2",
                    "predicates": ["biolink:related_to"]
                },
                "e03": {
                    "subject": "n0",
                    "object": "n3",
                    "predicates": ["biolink:related_to"]
                }
            }
        }
    }
}
```

**Comment by tursynay** [comment]
Need to assign one person per ARA

**Comment by saramsey** [comment]
The original query graph seems to work (as in, not generate an error) when I put it directly into the JSON box on arax.ncats.io:  [results here](https://arax.ncats.io/?r=12813). 

Results may be a bit more interesting if we set `is_set` to `true` on the gene node (`n0`):
```
{
            "nodes": {
                "n0": {
                    "categories": ["biolink:Gene"],
                    "is_set": true
                },
                "n1": {
                    "ids": ["CHEBI:45783"],
                    "categories": ["biolink:ChemicalSubstance"]
                },
                "n2": {
                    "ids": ["MONDO:0005301"],
                    "categories": ["biolink:Disease"]
                },
                "n3": {
                    "categories": ["biolink:ChemicalSubstance"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:related_to"]
                },
                "e02": {
                    "subject": "n0",
                    "object": "n2",
                    "predicates": ["biolink:related_to"]
                },
                "e03": {
                    "subject": "n0",
                    "object": "n3",
                    "predicates": ["biolink:related_to"]
                }
            }
}
```
[Results here](https://arax.ncats.io/?r=12814)

We also may want to do a Fisher Exact Test overlay (connecting the drug to the disease).

**Comment by saramsey** [comment]
Tagging @dkoslicki

**Comment by dkoslicki** [comment]
Huh, I'm not seeing an ARAX error on my end: 48392bc9-f323-4f38-aa53-c91ca944b99c
![image](https://user-images.githubusercontent.com/6362936/122429769-05bd4700-cf61-11eb-96ce-54ff41ffa38f.png)

Maybe an ARS issue? I can't reproduce this issue.

**Comment by dkoslicki** [comment]
@rtroper Do you mind trying again and letting me know if you still see an error?

**Comment by rtroper** [comment]
> @rtroper Do you mind trying again and letting me know if you still see an error?

Nice, it does look like it's working now. I just posted the query to https://ars-dev.transltr.io/ars/api/submit and I'm getting this, below. The pk is 5192905f-323b-482b-950d-045448e26e59. Maybe you've implemented some changes since I last ran the TRAPI query.

![image](https://user-images.githubusercontent.com/18222763/122436825-fbde1880-cf4d-11eb-9e8e-6c289d40abde.png)

**Comment by dkoslicki** [comment]
Great! @tursynay do you mind unassigning me (and perhaps assigning others for the ARAs that are returning errors)?

**Comment by tursynay** [comment]
Dear ARA leads, I have added you to the issue, please take a look and if there are questions, let us know.

**Comment by vgardner-renci** [comment]
Break down per ARA/KP

**Comment by rtroper** [comment]
Noting, that this issue has been broken out into the following issue: #50, #51, #52, #53, #54, #55, #56, #57, #58, #59, #60, #62, #63, #64. As of 7/1, here are the [results of running this query through the ARS](https://arax.ncats.io/?source=ARS&id=1da460fa-7447-41bb-a660-42d240b3acb1) (pk: 1da460fa-7447-41bb-a660-42d240b3acb1).

**Comment by vgardner-renci** [comment]
Closed
