### ISSUE TITLE
Discuss workflow D “Explain” w Sergio Baranzini and Brett Smith

### ISSUE THREAD

**Issue by tursynay** [NCATSTranslator/minihackathons#42]
Explain why Crohn's Disease patients are susceptible to Parkinson’s? 
PK: [534cb1f8-5e0d-499e-9a9f-2b35ca933d3b](https://arax.ncats.io/?source=ARS&id=534cb1f8-5e0d-499e-9a9f-2b35ca933d3b) 

This issue is for the ARAs to take a look at the errors in the results. See the pk above.
![Workflow D](https://user-images.githubusercontent.com/65674466/122436738-eb2da280-cf4d-11eb-8070-136b994fe82e.png)

(Edited AS 2021-06-23: added TRAPI query below)
```
{
  "message": {
    "query_graph": {
      "edges": {
        "e00": {
          "object": "n01",
          "subject": "n00"
        },
        "e01": {
          "object": "n02",
          "subject": "n01"
        }
      },
      "nodes": {
        "n00": {
          "categories": [
            "biolink:Disease"
          ],
          "ids": [
            "DOID:14330"
          ]
        },
        "n01": {
          "categories": [
            "biolink:NamedThing"
          ]
        },
        "n02": {
          "categories": [
            "biolink:Disease"
          ],
          "ids": [
            "DOID:8778"
          ]
        }
      }
    }
  }
}
```

**Comment by colleenXu** [comment]
@tursynay could you change the PK above to 534cb1f8-5e0d-499e-9a9f-2b35ca933d3b ? This is the ARS's PK. What is currently in your message is improving agent's response.

**Comment by colleenXu** [comment]
@andrewsu Does the work below sound right?

It looks like this is a Disease X -> NamedThing ➡️ Disease Y query. 

My understanding is that BTE isn't expected to accept this kind of path. This instead should be an Explain-type query with Disease X -> NamedThing ⬅️ Disease Y (emoji is for emphasis). 

Then, we'd work to get BTE working with Explain-type queries.
