### ISSUE TITLE
Improving returning an error on Workflow C query

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#55]
0fd681f9-4b08-43d4-b7a3-cf6e561d49af

![image](https://user-images.githubusercontent.com/83781286/123323113-16dafa80-d503-11eb-967e-1929b70600d7.png)

**Comment by rtroper** [comment]
```

{
  "callback": "http://0.0.0.0:8000/ars/api/messages/ec3fb09f-c583-4beb-9d36-3ac5ce63535e",
  "logs": [
    {
      "level": "INFO",
      "message": "ARS info: {\n  &quot;description&quot;: &quot;Couldn&#x27;t find edge corresponding to n2&quot;,\n  &quot;message&quot;: {},\n  &quot;status&quot;: &quot;Bad Request&quot;\n}\n"
    },
    {
      "level": "INFO",
      "message": "ARS info: tr_ars.Server: nginx/1.16.1"
    },
    {
      "level": "INFO",
      "message": "ARS info: tr_ars.Date: Thu, 01 Jul 2021 16:04:16 GMT"
    },
    {
      "level": "INFO",
      "message": "ARS info: tr_ars.Content-Type: application/json"
    },
    {
      "level": "INFO",
      "message": "ARS info: tr_ars.Content-Length: 106"
    },
    {
      "level": "INFO",
      "message": "ARS info: tr_ars.Connection: keep-alive"
    },
    {
      "level": "INFO",
      "message": "ARS info: tr_ars.reason: BAD REQUEST"
    },
    {
      "level": "INFO",
      "message": "ARS info: tr_ars.url: https://ia.healthdatascience.cloud/api/v1.1/query"
    }
  ],
  "max_results": 100,
  "message": {
    "query_graph": {
      "edges": {
        "e01": {
          "object": "n1",
          "predicates": [
            "biolink:related_to"
          ],
          "subject": "n0"
        },
        "e02": {
          "object": "n2",
          "predicates": [
            "biolink:related_to"
          ],
          "subject": "n0"
        },
        "e03": {
          "object": "n3",
          "predicates": [
            "biolink:related_to"
          ],
          "subject": "n0"
        }
      },
      "nodes": {
        "n0": {
          "categories": [
            "biolink:Gene"
          ]
        },
        "n1": {
          "categories": [
            "biolink:ChemicalSubstance"
          ],
          "ids": [
            "CHEBI:45783"
          ]
        },
        "n2": {
          "categories": [
            "biolink:Disease"
          ],
          "ids": [
            "MONDO:0005301"
          ]
        },
        "n3": {
          "categories": [
            "biolink:ChemicalSubstance"
          ]
        }
      }
    }
  },
  "validation_result": {
    "message": "Returned response is not TRAPI: {\n  &quot;description&quot;: &quot;Couldn&#x27;t find edge corresponding to n2&quot;,\n  &quot;message&quot;: {},\n  &quot;status&quot;: &quot;Bad Request&quot;\n}\n",
    "size": "2 kB",
    "status": "NA",
    "version": "1.1.1"
  }
}
```

**Comment by rtroper** [comment]
@brettasmi @suihuang-ISB - Could you comment on status?

**Comment by brettasmi** [comment]
This looks like a non-linear query, which we don't support currently. From what I can tell, the query graph looks something like:

(ChemicalSubstance: Imatinib)
                    |
               (Gene: Any) --- (Disease: Multiple Sclerosis)
                    |
(ChemicalSubstance: Any)

Is that correct @rtroper ?

**Comment by rtroper** [comment]
> This looks like a non-linear query, which we don't support currently. From what I can tell, the query graph looks something like:
> 
> (ChemicalSubstance: Imatinib)
> |
> (Gene: Any) --- (Disease: Multiple Sclerosis)
> |
> (ChemicalSubstance: Any)
> 
> Is that correct @rtroper ?

That's right, @brettasmi. It's a central, unconstrained node directly connected to three other nodes, two specified and one unconstrained

**Comment by brettasmi** [comment]
Thanks @rtroper 

I take it the intention is to do repurposing at the same targets as imatinib then?

Could the query be approximately stated in english as "Find all Genes that are associated with Imatinib and MS, then find all ChemcialSubstances that are associated with those Genes?"

**Comment by rtroper** [comment]
> I take it the intention is to do repurposing at the same targets as imatinib then?
> 
> Could the query be approximately stated in english as "Find all Genes that are associated with Imatinib and MS, then find all ChemcialSubstances that are associated with those Genes?"

Yeah, I think that's a good way to put it.

**Comment by brettasmi** [comment]
We don't currently have these non-linear queries on the road map just yet, though we could probably implement it as two separate linear queries. I'm not sure which one would be more work at this point. As noted in the tag above, this is on the back burner for us.

**Comment by jenndoug** [comment]
mid-to-late September; major rework to SPOKE

**Comment by suihuang-ISB** [comment]
I would say, as  intensely discussed, this is "outside the scope" I am not sure we should spend energy on making  non-linear qgraphs an option ... This issue only exists because of the way this use case has been framed and is not generalizable. 
The more general functionality for future could be a multi-node query looking for some explanatory spanning tree... We could revisit this after the Dec demo.
