### ISSUE TITLE
Errors on Workflow C query

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#59]
0fd681f9-4b08-43d4-b7a3-cf6e561d49af

![image](https://user-images.githubusercontent.com/83781286/123323113-16dafa80-d503-11eb-967e-1929b70600d7.png)

**Comment by vemonet** [comment]
Hi, is it possible to have more informations about the query run?

The query ID is not sufficient to reproduce and fix the query: https://arax.ncats.io/?source=ARS&id=0fd681f9-4b08-43d4-b7a3-cf6e561d49af

![Screenshot from 2021-06-25 16-53-05](https://user-images.githubusercontent.com/3778439/123443097-dd26f400-d5d5-11eb-98fe-32551bc9bc7f.png)


Plus it seems there are new TRAPI 1.1 requirements which have broken the tests for most KP and ARA (not only OpenPredict) 

What are those changes? Because we were valid when TRAPI 1.1 went out

**Comment by rtroper** [comment]
@vemonet - Specifically, this refers to Query 2 of workflow C. See issue #34 for a description of the workflow and issue #40, where this issue was originally reported. Reproducing Query 2 below:

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:Gene"]
                },
                "n1": {
                    "ids": ["CHEBI:45783"],
                    "categories": ["biolink:ChemicalSubstance"]
                },
                "n2": {
                    "ids": ["MONDO:0005301"],
                    "categories": ["biolink:Disease"]
                },
                "n3": {
                    "categories": ["biolink:ChemicalSubstance"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:related_to"]
                },
                "e02": {
                    "subject": "n0",
                    "object": "n2",
                    "predicates": ["biolink:related_to"]
                },
                "e03": {
                    "subject": "n0",
                    "object": "n3",
                    "predicates": ["biolink:related_to"]
                }
            }
        }
    }
}
```

**Comment by vemonet** [comment]
This is the response we are returning:

```json
{
  "message": {
    "knowledge_graph": {
      "edges": {},
      "nodes": {}
    },
    "query_graph": {
      "edges": {
        "e01": {
          "object": "n1",
          "predicates": [
            "biolink:related_to"
          ],
          "subject": "n0"
        },
        "e02": {
          "object": "n2",
          "predicates": [
            "biolink:related_to"
          ],
          "subject": "n0"
        },
        "e03": {
          "object": "n3",
          "predicates": [
            "biolink:related_to"
          ],
          "subject": "n0"
        }
      },
      "nodes": {
        "n0": {
          "categories": [
            "biolink:Gene"
          ]
        },
        "n1": {
          "categories": [
            "biolink:ChemicalSubstance"
          ],
          "ids": [
            "CHEBI:45783"
          ]
        },
        "n2": {
          "categories": [
            "biolink:Disease"
          ],
          "ids": [
            "MONDO:0005301"
          ]
        },
        "n3": {
          "categories": [
            "biolink:ChemicalSubstance"
          ]
        }
      }
    },
    "results": []
  }
}
```

How do we figure out what is not TRAPI 1.1 compliant?

**Comment by cbizon** [comment]
The reasoner validator should be able to point out particular issues: https://pypi.org/project/reasoner-validator/

**Comment by vemonet** [comment]
Thanks @cbizon !

I tried it on our TRAPI response:

```python
validate(response['message'], "Message", "1.1.0")
```

It is returning this error:

```bash
TypeError: add_file() got an unexpected keyword argument 'query_graph'
```

But according to the ReasonerAPI latest docs it seems like the `query_graph` should be part of the Message, or we should remove it now?

**Comment by cbizon** [comment]
I could be wrong here, but I don't think you need to pull out `message`.   So it should be:
```
validate(response,"Message","1.1.0")
```
@patrickkwang is that right?

**Comment by patrickkwang** [comment]
No, @vemonet is correct, you should pass a Message if you want to validate a Message. The thing above validates for me. I'm not sure where that error message is coming from; reasoner-validator does not define an `add_file()` function. Are you using the latest version (2.1.0)?

**Comment by vemonet** [comment]
Indeed Patrick the `add_file` error was from the same line but not from the validator library

The `reasoner-validator` will be helpful now that it is integrated to our tests suite. I could not find it in the SRI wiki page though, should I add it there? Or is it already indexed somewhere else?

I ran the query on the ARS query, and it validates properly now (cf. run 693d4d00-1000-48c2-9ea6-9905345fd3d4 )

Thanks for the help!
