### ISSUE TITLE
ICEES returning error on Workflow C query

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#60]
0fd681f9-4b08-43d4-b7a3-cf6e561d49af

![image](https://user-images.githubusercontent.com/83781286/123323113-16dafa80-d503-11eb-967e-1929b70600d7.png)

**Comment by diatomsRcool** [comment]
<img width="1440" alt="Screen Shot 2021-07-01 at 10 42 32 AM" src="https://user-images.githubusercontent.com/5140552/124160127-2a351b00-da59-11eb-96f5-054daa251636.png">
Out of scope - handling gracefully now
