### ISSUE TITLE
Robokop returning error on Workflow C query

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#62]
0fd681f9-4b08-43d4-b7a3-cf6e561d49af

![image](https://user-images.githubusercontent.com/83781286/123323113-16dafa80-d503-11eb-967e-1929b70600d7.png)

**Comment by cbizon** [comment]
I don't think this should be registered with the ARS

**Comment by MarkDWilliams** [comment]
Robokop has been deactivated in the ARS instance.  It was activated by mistake during the migration to the ITRB deployed environment
