### ISSUE TITLE
ARAX error on three hop query

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#64]
https://arax.ncats.io/?source=ARS&id=8432eb9d-783c-4a0e-9343-298f67cac6bb

**Comment by vgardner-renci** [comment]
@edeutsch request for update

**Comment by vgardner-renci** [comment]
@edeutsch request for update

**Comment by edeutsch** [comment]
This has been fixed so there is no longer an error:
https://arax.ncats.io/?r=15818
although there are no results found for this particular query

**Comment by dkoslicki** [comment]
As mentioned here and in #75, ARAX is no longer returning an error. No KP is returning information for even the first hop
