### ISSUE TITLE
Query results not making sense

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#65]
https://arax.ncats.io/?source=ARS&id=0cdc5dab-49ba-4a3d-9688-8f36f95b964d 

Results are not making sense. E.g. coumarin being in the results and also immunology

**Comment by saramsey** [comment]
Message received. I am investigating. https://github.com/RTXteam/RTX/issues/1538

**Comment by saramsey** [comment]
My team has advised me that this issue is likely to be resolved when the new version of the RTX-KG2 knowledge graph (KG2.6.7) is deployed into production.

**Comment by saramsey** [comment]
Just an FYI on this issue, `biolink:correlated_with` will not give you all the related phenotypes. Broadening the query using `biolink:related_to` gives 16 associated phenotypes and diseases:
```
{
  "edges": {
    "N1": {
      "object": "n1",
      "predicates": [
        "biolink:has_normalized_google_distance_with"
      ],
      "relation": "N1",
      "subject": "n0"
    },
    "e0": {
      "object": "n1",
      "predicates": [
        "biolink:correlated_with",
        "biolink:related_to"
      ],
      "subject": "n0"
    }
  },
  "nodes": {
    "n0": {
      "ids": [
        "MONDO:0005359"
      ],
      "is_set": false
    },
    "n1": {
      "categories": [
        "biolink:DiseaseOrPhenotypicFeature"
      ],
      "is_set": false
    }
  }
}

```

**Comment by vgardner-renci** [comment]
@edeutsch to test

**Comment by edeutsch** [comment]
Re-issuing this query seems to yield a better result with RTX-KG2.6.7:
https://arax.ncats.io/?r=15819
coumarin and immunology are no longer in the results list. Overall results seem better.
okay to close?

**Comment by vgardner-renci** [comment]
@cbizon ok to close?
