### ISSUE TITLE
ARAX not talking to ICEES

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#67]
https://arax.ncats.io/?source=ARS&id=0cdc5dab-49ba-4a3d-9688-8f36f95b964d

**Comment by edeutsch** [comment]
Status is: we are currently use ICEES for overlaying/enriching, but not expanding. but planning to do soon.

**Comment by tursynay** [comment]
Hao Zhu is tagged on the RTX issue and is working on this.

**Comment by vgardner-renci** [comment]
@xu-hao any progress to update?

**Comment by tursynay** [comment]
Can be closed
