### ISSUE TITLE
ARAX not converting NCBIGene ID to ENSEMBL_ID

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#72]
DILI Drug repurposing query - gene to chem substance (Node Normalizer is down 6/24 and results are not complete):
Genes from Kara: 
class I HLA-A - NCBIGene:3105
class I HLA-B - NCBIGene:3106
ERAP2 - NCBIGene:64167
EXOC4 - NCBIGene:60412 -  selected first, used the ENSEMBL id (since NodeNorm was down). 

Chris B thinks that there should be a translation happening when NCBIGene Id then ARAX should convert the ID to ENSEMBL ID and pass it down the chain. Eric thinks that this is not happening. 

https://arax.ncats.io/?source=ARS&id=64f1182b-3463-4321-ac41-8715a14995e6

**Comment by vgardner-renci** [comment]
@edeutsch to test

**Comment by edeutsch** [comment]
This is fixed here:
https://arax.ncats.io/?r=15793

**Comment by vgardner-renci** [comment]
@edeutsch indicates this is fixed
