### ISSUE TITLE
ARAX error on Workflow B query

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#75]
https://arax.ncats.io/?source=ARS&id=0445a10f-05b6-4bf3-82a5-586a55655e1c

**Comment by dkoslicki** [comment]
This is fixed now: https://arax.ncats.io/test/?r=16138 but note the query is returning now results as no KP or ARA ARAX is connected to is returning results. I assume COHD _should_ return results, so it might be an issue of different identifiers, or stale data. Would need to confirm with the COHD/Clinical team why this is the case
