### ISSUE TITLE
Improving agent no results in Workflow B query

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#79]
https://arax.ncats.io/?source=ARS&id=0445a10f-05b6-4bf3-82a5-586a55655e1c

**Comment by vgardner-renci** [comment]
{
  "edges": {
    "e0": {
      "object": "n1",
      "predicates": [
        "biolink:correlated_with"
      ],
      "subject": "n0"
    },
    "e1": {
      "object": "n2",
      "predicates": [
        "biolink:condition_associated_with_gene"
      ],
      "subject": "n1"
    },
    "e2": {
      "object": "n3",
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n2"
    }
  },
  "nodes": {
    "n0": {
      "ids": [
        "MONDO:0005359"
      ],
      "name": "drug-induced liver injury"
    },
    "n1": {
      "categories": [
        "biolink:DiseaseOrPhenotypicFeature"
      ],
      "name": "Disease Or Phenotypic Feature"
    },
    "n2": {
      "categories": [
        "biolink:Gene"
      ],
      "name": "Gene"
    },
    "n3": {
      "categories": [
        "biolink:ChemicalSubstance"
      ],
      "name": "Chemical Substance"
    }
  }
}

**Comment by vgardner-renci** [comment]
```{
  "description": "imProving Agent requires that qNodes with identifier also specify a biolink category; returning empty message...",
  "message": {},
  "status": "Query unprocessable",
  "validation_result": {
    "message": "",
    "size": "0.55 kB",
    "status": "PASS",
    "version": "1.1.1"
  }
}```

**Comment by brettasmi** [comment]
Related to #11 for us

**Comment by tursynay** [comment]
Kara mentioned that Hao wrote a tool that chains KPs and ARAs (semi-manual, can run a three hop successfully), and this query returns results. Kara will keep the group informed

**Comment by suihuang-ISB** [comment]
@brettasmi  - can we discuss this - see https://github.com/suihuanglab/improving-agent/issues/42  
and close?

**Comment by suihuang-ISB** [comment]
We should discuss this under #11 and suihuanglab/improving-agent#42
