### ISSUE TITLE
Workflow D Discussion

### ISSUE THREAD

**Issue by brettasmi** [NCATSTranslator/minihackathons#82]
Workflow D will showcase the ability of Translator to "explain" an observed connection between two biological concepts. As a start, the imProving Agent team suggested the following three questions:

1. Why do Crohn's disease patients have a higher risk to develop Parkinson’s disease?
2. Why do SSRI (a group of anti-depressants) have cardio-protective effect?
3. Why are serum kynurenine and tryptophan in COVID-19 patients anti-correlated?

Queries to address these questions are proposed in #81

Initial discussion can be found in #42

**Comment by brettasmi** [comment]
Some notes from this morning's call:

General notes:
- We should probably come up with a new name for this type of query since "Explain" is being used elsewhere with a different meaning. Maybe "Connect these things," "Connect2," or simply "Connect"
- These are almost all 2+ hop queries and thus the focus was on ARAs, but we should try to understand where the individual one-hops farmed out to the KPs work or don't

For the [Crohn's -- Parkison's query](https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowD/parkinsons-crohns.json):
- The positive control for this query is the gene LRRK2
- This query returns many good results from the ARAs
- It might be best to modify this query to search for `biolink:Gene` instead of `biolink:NamedThing`

For the [SSRI -- Heart Disease query](https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowD/ssri-heart-disease.json):
- We did not find many of the expected genes here
- We would hope to see some results from the clinical providers
- Created a one-hop version of this query to see what we could find see #125 

For the [tryptophan -- kynurenine query](https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowD/tryptophan-kynurenine-with-curie.json):
- This query attempts to retrieve the metabolic reactions that connect these two compounds
- How should we handle reaction modeling? Query as specified is pretty specific to SPOKE, but it seems like Biolink might expect them to be different. Should we consider collapsing enzymatic activity and reaction into one node? 
- Tried a version of this with one fewer hop without much success.

From ferritin -- metformin query added in #125
- This stems from a real-world scenario where a patient has high ferritin levels and a biotech contact suggests that metformin may lower ferritin. Can we figure out why?
- We expect to find this through protein-protein interactions
- No "ground truth" for this yet, so we don't know have a positive control

@suihuang-ISB please fill in additional details as appropriate to help others understand this workflow.

**Comment by suihuang-ISB** [comment]
"Explain" was the term used by NCATS (Tyler) and I think we can keep it: This is mostly about connecting two terms via an "explanatory" multi-hop path whose length and content is not specified.. There have been discussions to creatd an OPERATION for this.

For the biomedical relevance and background I have slide that I will put in the appropriate folder in NCATs Google shared drive
