### ISSUE TITLE
Cam no results in Workflow D.1 query

### ISSUE THREAD

**Issue by vgardner-renci** [NCATSTranslator/minihackathons#98]
https://arax.ncats.io/?source=ARS&id=580dfdb6-9e6c-4ac0-a937-ef184363f04f

![image](https://user-images.githubusercontent.com/83781286/124955876-69c5af00-dfe5-11eb-9851-97d6068c5f00.png)

**Comment by balhoff** [comment]
@vgardner-renci where can I view the query? Thanks!
